#!/bin/sh
#-----------------------------------------------------
# IceWM - startup file
# by Mizu.Taifux
# 2023
#-----------------------------------------------------
# systray
#-----------------------------------------------------
# sleep 2
# volumeicon &
# compton &
# nm-applet &
#-----------------------------------------------------
# Background wallpaper
# nitrogen --restore &
#-----------------------------------------------------
# Desktop Icons
# exec pcmanfm --desktop &
#-----------------------------------------------------
# Resolução da tela
#-----------------------------------------------------
# exec xrandr --output VGA1 --mode "1440x900_60.00"
# ----------------------------------------------------
exec xrandr --output VGA1 --mode "1920x1080" &
exec icewmbg &
exec picom &
exec volumeicon